spring.application.name=resilience-gateway
server.port=8082
management.endpoints.web.exposure.include=health,circuitbreakers
management.endpoint.health.show-details=always
resilience4j.circuitbreaker.instances.exampleCircuitBreaker.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.exampleCircuitBreaker.slidingWindowSize=10
resilience4j.circuitbreaker.instances.exampleCircuitBreaker.failureRateThreshold=50
resilience4j.circuitbreaker.instances.exampleCircuitBreaker.waitDurationInOpenState=10000
resilience4j.circuitbreaker.instances.exampleCircuitBreaker.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.exampleCircuitBreaker.minimumNumberOfCalls=5
